### ISSUE TITLE
Error when running the classifier

### ISSUE THREAD

**Issue by thisisthechris** [bluemonk482/emotionannotate#1]
Hi All,

I'm working on creating a reusable development environment for this project using Virtualbox, Vagrant and Ansible. I'm very close, but at the moment at get the following error whenever I try to run Classifer.py:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/vagrant/src/Classifier.py", line 41, in classifier
    scaling(dir,emo)
  File "/vagrant/src/Classifier.py", line 12, in scaling
    subprocess.call(cmd2, stdout=outfile2)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

This occurs for both the web interface and the command line tool. It's also repeated another four times (I assume for each emotion). The scripts then hang and become unresponsive.

I think it's an issue with the output files. I'm going to try removing them and see what happens.

C

**Comment by adtsakal** [comment]
Hi Chris,

Thank you. Could you try running Classification.py instead of Classifier.py?
It should run and ask you to provide two input directories (possibly with a
warning).

Thanks,
Adam

**Comment by thisisthechris** [comment]
I think I've figured it out. LibSVM in the repo is a local compiled version, so it won't execute under my vagrant environment. I'll swap this for: https://packages.debian.org/squeeze/libsvn-dev

If you want to take a look for yourself the branch I'm currently working on is here: https://github.com/i-DAT/emotionannotate/tree/add-vagrant-development-env

**Comment by thisisthechris** [comment]
Have got it working by installing https://packages.debian.org/wheezy/devel/libsvm-tools and tweaking the code to use those libs rather than the ones committed into the repo. 
<img width="1330" alt="screenshot 2016-01-05 13 11 31" src="https://cloud.githubusercontent.com/assets/181447/12115929/ea1bf642-b3ad-11e5-84bc-29b234455df9.png">
